### ISSUE TITLE
Setup repo

### ISSUE THREAD

**Issue by lboxell** [gentzkow/VirusGPS#3]

**Comment by lboxell** [comment]
@gentzkow @jcconway,

Do you use the gslab-econ template for your projects with Hunt? Or is there a different template I should be aware of?

**Comment by jcconway** [comment]
@lboxell on past projects I believe we've used a simpler template like [gentzkow/template](https://github.com/gentzkow/template), which doesn't incorporate SCons. I'll defer to @gentzkow  as to which template he'd like to use for this project.

**Comment by lboxell** [comment]
@jcconway, That works for me. I'll just switch over.

**Comment by lboxell** [comment]
Closing.

Pull request in #4.
